### ISSUE TITLE
Icecast folder in docker compose

### ISSUE THREAD

**Issue by jokerigno** [ssjoleary/mopice#1]
Hi,

I started testing your docker (THANK YOU) and noticed that there's an error in the docker compose file.

resourse should be

    - .resources/silence.mp3:/usr/share/icecast2/silence.mp3
against

    - .resources/silence.mp3:/usr/share/icecast/silence.mp3

I changed after container creation and magically started working.

**Comment by ssjoleary** [comment]
Thanks @jokerigno! Well spotted, I've updated this 👍
